language: node_js
node_js:
  - "10"
  - "12"
  - "13"
install:
  - npm i
  - npm i codecov
before_script:
  - npm run build
script:
  - npm run cov
after_script:
  - codecov
  - test $TRAVIS_NODE_VERSION = 10 && travis_wait scripts/deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: c041da81e3e9
